apiVersion: v1
kind: Service
metadata:
  name: {{ include "ping-pong-api-helm.fullname" . }}
  labels:
    {{- include "ping-pong-api-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "ping-pong-api-helm.selectorLabels" . | nindent 4 }}
